<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Cap\CustomerRequest\Block\Rma\Dashboard */ ?>

<?php if ($block->isloggedIn() && $block->isRmaRequestEnabled()): ?>

    <?php echo $block->getChildHtml('cap.customer.request.rma.form') ;?>
    <?php echo $block->getChildHtml('cap.customer.request.rma.history') ;?>

<?php else: ?>
    <div class="message error">
        <div><?php /* @escapeNotVerified */ echo __('You must be logged in.'); ?></div>
    </div>
<?php endif; ?>
