<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Cap\CustomerRequest\Block\Rma\Dashboard */ ?>

<?php $ordersCollection = $block->getCustomerOrders() ?>
<?php $conditionsLink = $block->getUrl($block->getRmaConditionsLink()) ?>
<?php $jsIncrementIds = []; ?>

<div class="block block-dashboard-orders">
    <div class="block-title order">
        <strong><?php /* @escapeNotVerified */ echo __('My Orders') ?></strong>
        <span class="subtitle"><?php /* @escapeNotVerified */ echo __('%1return conditions%2', '<a href="' . $conditionsLink .'">', '</a>') ?></span>
    </div>
    <div class="table-wrapper orders-history">
        <?php if ($ordersCollection && count($ordersCollection)): ?>
            <table class="data table table-order-items history" id="my-orders-table">
                <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Order #') ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                    <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Order Total') ?></th>
                    <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                    <th scope="col" class="col actions"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \Magento\Sales\Model\Order $order */ ?>
                <?php foreach ($ordersCollection as $order): ?>
                    <?php if ($block->isOrderStatusAllowed($order)): ?>
                        <?php $jsIncrementIds[] = $order->getIncrementId(); // Js variable to differentiate each popup modal ?>
                        <tr>
                            <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $order->getIncrementId() ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($order->getCreatedAt()) ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $order->formatPrice($order->getGrandTotal()) ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $order->getStatusLabel() ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <?php // modal trigger ?>
                                <a href="#" id="modal-trigger-order-<?php echo $order->getIncrementId(); ?>" class="action view">
                                    <span><?php /* @escapeNotVerified */ echo __('Return') ?></span>
                                </a>
                                <?php // modal content ?>
                                <div id="popup-modal-<?php echo $order->getIncrementId() ?>">
                                    <?php $items = $block->getOrderItems($order) ?>

                                    <h3><?php echo __('Please select one or more product(s)') ?></h3>

                                    <form id="rma-form-<?php echo $order->getIncrementId() ?>"
                                          action="<?php echo $block->getFormAction() ?>"
                                          method="post"
                                          data-mage-init='{"validation":{}}'>
                                        <fieldset class="fieldset create stock-request">

                                            <input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>">
                                            <input type="hidden" name="orderId[]" value="<?php echo $order->getId() ?>">
                                            <input type="hidden" name="customerId[]" value="<?php echo $block->getCustomer()->getId() ?>">

                                            <?php foreach ($items as $key => $item): ?>
                                                <?php $html = '<strong>' . $item['sku'] . '</strong><br>' ?>
                                                <?php $html .= $item['name'] . ' | ' . $item['attributes'] ?>
                                                <div class="field product">
                                                    <input type="checkbox" id="order-item-<?php echo $item['sku'] ?>" name="orderItem[]">
                                                    <label for="orderItem[]"><?php echo $html ?></label>
                                                </div>
                                                <div class="field rma-type">
                                                    <?php // todo: get all types & loop for radio button (only one choice) | css float right ?>
                                                    <input type="checkbox" id="rma-type-<?php echo $item['sku'] ?>" name="orderItem[]">
                                                    <label for="orderRefund[]">refund</label>
                                                </div>
                                            <?php endforeach; ?>

                                            <?php // todo: customer comment textarea ?>
                                            <div class="field comment">
                                                <textarea></textarea>
                                            </div>

                                            <button type="submit" name="submit[]" class="hidden-button"><?php /* @escapeNotVerified */ echo __('Submit') ?></button>

                                        </fieldset>
                                    </form>

                                    <div class="rma-popup-message"><?php echo $block->getRmaPopupMessage() ?></div>
                                </div>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?php if ($block->getPagerHtml()): ?>
                <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
            <?php endif ?>
        <?php else: ?>
            <div class="message info empty">
                <?= /* @escapeNotVerified */ __('You have no orders that meet our %1return conditions%2.', '<a href="' . $conditionsLink .'">', '</a>') ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($, modal) {
        var ids = <?php echo json_encode($jsIncrementIds) ?>;
        $.each(ids, function (key, id) {
            var form = $('#rma-form-'+id);
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Order <span class="subtitle">'+id+'</span>',
                modalClass: 'cap-customer-request-modal',
                buttons: [{
                    text: $.mage.__('Submit'),
                    class: 'action primary',
                    click: function () {
                        form.find('button[type="submit"]').click();
                    }
                }]
            };
            var popup = modal(options, $('#popup-modal-'+id));
            $('#modal-trigger-order-'+id).click(function () {
                $("#popup-modal-"+id).modal('openModal');
            });
        })
    });
</script>
