<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Cap\CustomerRequest\Block\Rma\Dashboard */ ?>

<?php $customerId = $block->getCustomer()->getId() ?>
<?php $collection = $block->getRmaCustomerHistory($customerId) ?>

<div class="block block-dashboard-returns">
    <div class="block-title order">
        <strong><?php /* @escapeNotVerified */ echo __('My Returns') ?></strong>
    </div>
    <div class="table-wrapper returns-history">
        <?php if ($collection && count($collection)): ?>
            <table class="data table table-return-items history" id="my-returns-table">
                <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Return') ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Return #') ?></th>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                    <th scope="col" class="col order"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                    <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                    <th scope="col" class="col actions"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \Cap\CustomerRequest\Model\Rma $item */ ?>
                <?php foreach ($collection as $item): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Return #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $item->getEntityId() ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($item->getCreatedAt()) ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col order">
                            <a href="<?php echo $block->getOrderUrl($item->getOrderId()) ?>">
                                <?php /* @escapeNotVerified */ echo $block->getOrderById($item->getOrderId())->getIncrementId() ?>
                            </a>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $block->getStatusLabel($item->getStatus()) ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <?php // todo: request details link ;?>
                            <a href="<?php /* @escapeNotVerified */ // echo $block->getViewUrl($_order) ?>" class="action view">
                                <span><?php /* @escapeNotVerified */ echo __('Details') ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?php // TODO: pager ?>
        <?php else: ?>
            <div class="message info empty">
                <?= /* @escapeNotVerified */ __('You have no request.') ?>
            </div>
        <?php endif; ?>
    </div>
</div>
