<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Cap\CustomerRequest\Block\Customer\Dashboard */ ?>

<?php $helper = $this->helper('Cap\CustomerRequest\Helper\Data'); ?>
<?php $ordersCollection = $block->getOrdersCanRequest(); ?>

<?php
//
//$test = $block->test();
//
//echo '<pre>';
//print_r($test);
//echo '</pre>';
//
?>

<?php if ($block->isloggedIn()): ?>
    <?php if ($ordersCollection->count()): ?>
        <?php /** @var \Magento\Sales\Model\Order $order */ ?>
        <?php foreach ($block->getOrdersCanRequest() as $order): ?>
            <?php $order = $block->getLoadOrderById($order->getId()); ?>
            <?php $orderItems = $order->getAllVisibleItems(); ?>
            <?php foreach ($orderItems as $item): ?>
                <?php if ($item->getProductType() == 'configurable'): ?>
                    <?php $sku = $item->getProductOptions()['simple_sku']; ?>
                    <?php $product = $block->getLoadProductBySku($sku); ?>
                    <?php echo $product->getName(); ?>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="message error">
            <?= /* @escapeNotVerified */ __('You have no orders that meet our %1return policy%2.', '<a href="' . $block->getUrl($helper->getConfigRmaPolicyLink()) .'">', '</a>') ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message error">
        <div><?php /* @escapeNotVerified */ echo __('You must be logged in.'); ?></div>
    </div>
<?php endif; ?>