<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Cap\CustomerRequest\Block\Customer\Dashboard */ ?>

<?php $helper = $this->helper('Cap\CustomerRequest\Helper\Data') ?>
<?php $ordersCollection = $block->getOrders() ?>

<?php if ($ordersCollection && count($ordersCollection)): ?>
    <?php $jsIncrementIds = []; ?>
    <?php /** @var \Magento\Sales\Model\Order $order */ ?>
    <?php foreach ($ordersCollection as $order): ?>
        <?php if ($block->isOrderStatusAllowed($order)): ?>
            <?php $jsIncrementIds[] = $order->getIncrementId(); // Js variable to differentiate each popup modal ?>

            <?php // modal trigger ?>
            <a href="#" id="modal-trigger-order-<?php echo $order->getIncrementId(); ?>">
                <?php echo $order->getIncrementId() ?>
            </a>

            <?php // modal content ?>
            <div id="popup-modal-<?php echo $order->getIncrementId() ?>">
                <?php $items = $order->getAllVisibleItems() ?>
                <form id="rma-form-<?php echo $order->getIncrementId() ?>"
                      action="<?php echo $block->getFormAction() ?>"
                      method="post"
                      data-mage-init='{"validation":{}}'>

                    <input name="form_key" type="hidden" value="<?php echo $helper->getFormKey() ?>">
                    <input type="hidden" name="orderId[]" value="<?php echo $order->getId() ?>">
                    <input type="hidden" name="customerId[]" value="<?php echo $block->getCustomer()->getId();?>">

                    <fieldset class="fieldset create stock-request">

                        <?php /** @var \Magento\Catalog\Model\Product $product */ ?>
                        <?php foreach ($items as $product): ?>
                            <?php // todo: simple, bundle etc... ?>
                            <?php if ($product->getProductType() == 'configurable'): ?>
                                <?php $sku = $product->getProductOptions()['simple_sku'] ?>
                                <div class="field option required">
                                    <label for="orderItem[]"><?php echo $product->getName(); ?></label>
                                    <input type="checkbox" name="orderItem[]" id="order-item-<?php echo $product->getId(); ?>">
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>

                        <button type="submit" name="submit[]" class="hidden-button"><?php /* @escapeNotVerified */ echo __('Submit') ?></button>

                    </fieldset>
                </form>
            </div>
        <?php endif; ?>

    <?php endforeach; ?>
<?php else: ?>
    <div class="message error">
        <?= /* @escapeNotVerified */ __('You have no orders that meet our %1return policy%2.', '<a href="' . $block->getUrl($helper->getConfigRmaPolicyLink()) .'">', '</a>') ?>
    </div>
<?php endif; ?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($, modal) {
        var ids = <?php echo json_encode($jsIncrementIds) ?>;
        $.each(ids, function (key, id) {
            var form = $('#rma-form-'+id);
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Order: '+id,
                modalClass: 'cap-request-modal',
                buttons: [{
                    text: $.mage.__('Submit'),
                    class: 'action primary',
                    click: function () {
                        form.find('button[type="submit"]').click();
                    }
                }]
            };
            var popup = modal(options, $('#popup-modal-'+id));
            $('#modal-trigger-order-'+id).click(function () {
                $("#popup-modal-"+id).modal('openModal');
            });
        })
    });
</script>
