<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Link template
 *
 * @var $block \Cap\CustomerRequest\Block\Product\View
 */
?>

<div class="stock-request-link">
    <a href="#" data-role="stock-request-modal-link"><?php /* @escapeNotVerified */ echo $block->getStockRequestLink(); ?></a>
</div>